# -*- coding: utf-8 -*-
"""totalpracs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mHFg9tF6pJ2aX2m34zpb2pxkNbnVKfqe

# PRAC 1
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt

# Load dataset
data = pd.read_csv("adv.csv")

# Clean columns names
data.columns = data.columns.str.strip().str.lower()

# Features and target
x = data[['tv', 'radio', 'newspaper']]
y = data['sales']

# Train-test split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

# ==========================================
# Model 1: TV only
# ==========================================
model_tv = LinearRegression()
model_tv.fit(x_train[['tv']], y_train)

y_pred_tv = model_tv.predict(x_test[['tv']])
print("TV only R²:", r2_score(y_test, y_pred_tv))

# ==========================================
# Model 2: All features
# ==========================================
model_all = LinearRegression()
model_all.fit(x_train, y_train)

y_pred_all = model_all.predict(x_test)
print("All features R2:", r2_score(y_test, y_pred_all))

# Print regression weights
print("\nRegression weights:")
print("Intercept (w0):", model_all.intercept_)
print("TV (w1):", model_all.coef_[0])
print("Radio (w2):", model_all.coef_[1])
print("Newspaper (w3):", model_all.coef_[2])

# Plot sales vs TV
plt.scatter(data['tv'], data['sales'])
plt.xlabel("TV Advertising")
plt.ylabel("Sales")
plt.title("Sales vs TV Advertising")
plt.show()

"""# PRAC2"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# ==========================================
# PART 1: Polynomial Regression using Sklearn
# (In-sample vs Out-sample errors)
# ==========================================
np.random.seed(0)

# Number of training points
N = 15

# Generate x values
x = np.random.uniform(-1, 1, N)
x = x.reshape(-1, 1)

# True polynomial coefficients (10th order)
coef = np.random.randn(11)

# True function f(x)
def f(x):
    y = 0
    for i in range(11):
        y += coef[i] * (x ** i)
    return y

# Generate noisy observations
y = f(x) + np.random.normal(0, 1, N).reshape(-1, 1)

# Test points for plotting
xtest = np.linspace(-1, 1, 400).reshape(-1, 1)

# Plot training data
plt.figure(figsize=(8, 5))
plt.scatter(x.flatten(), y.flatten(), label="Training data")

# Fit models of degree 2 and 10
for d in [2, 10]:
    poly = PolynomialFeatures(d)
    X_poly = poly.fit_transform(x)

    model = LinearRegression()
    model.fit(X_poly, y)

    # In-sample error (Ein)
    y_pred = model.predict(X_poly)
    Ein = mean_squared_error(y, y_pred)

    # Out-sample error (Eout)
    xt = np.random.uniform(-1, 1, 1000).reshape(-1, 1)
    Xt_poly = poly.transform(xt)
    y_true = f(xt)
    y_out = model.predict(Xt_poly)
    Eout = mean_squared_error(y_true, y_out)

    print(f"Degree {d} | Ein= {Ein:.4f} | Eout = {Eout:.4f}")

    # Plot model curve
    Xtest_poly = poly.transform(xtest)
    y_plot = model.predict(Xtest_poly)
    plt.plot(xtest, y_plot, label=f"Model degree({d})")

# Plot true function
plt.plot(xtest, f(xtest), label="True function f(x)")
plt.xlabel("x")
plt.ylabel("y")
plt.title("Polynomial Regression: Underfitting vs Overfitting")
plt.legend()
plt.ylim(-10, 10) # Set limit to visualize nicely
plt.show()


# ==========================================
# PART 2: Scenario 1 & Scenario 2 (using np.polyfit)
# ==========================================
np.random.seed(1)

# --- Scenario 1: True polynomial degree 10 with noise ---
x1 = np.random.uniform(-1, 1, N)
x1.sort()

coef_true = np.random.randn(11)

def f1(x):
    y = 0
    for i, c in enumerate(coef_true):
        y += c * (x ** i)
    return y

# Noisy observations
y1 = f1(x1) + np.random.normal(0, 1, N)

# Fit polynomial models
coef_deg2 = np.polyfit(x1, y1, 2)
coef_deg10 = np.polyfit(x1, y1, 10)

g2 = np.poly1d(coef_deg2)
g10 = np.poly1d(coef_deg10)

xx = np.linspace(-1, 1, 400)

plt.figure(figsize=(8, 5))
plt.scatter(x1, y1, label="15 data points (training data)")
plt.plot(xx, f1(xx), label="True function f(x)")
plt.plot(xx, g2(xx), label="Degree 2 model g2(x)")
plt.plot(xx, g10(xx), label="Degree 10 model g10(x)")
plt.title("Scenario 1: Degree 10 true function with noise")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.ylim(-10, 10)
plt.show()

# --- Scenario 2: True polynomial degree 50 (no noise) ---
coef_true50 = np.random.randn(51)

def f50(x):
    y = 0
    for i, c in enumerate(coef_true50):
        y += c * (x ** i)
    return y

x2 = np.random.uniform(-1, 1, 15)
x2.sort()
y2 = f50(x2)

# Fit models
coef2_s2 = np.polyfit(x2, y2, 2)
coef10_s2 = np.polyfit(x2, y2, 10)

p2 = np.poly1d(coef2_s2)
p10 = np.poly1d(coef10_s2)

plt.figure(figsize=(8, 5))
plt.scatter(x2, y2, label="15 data points (noiseless)")
plt.plot(xx, f50(xx), label="True function f(x)")
plt.plot(xx, p2(xx), label="Degree-2 model g2(x)")
plt.plot(xx, p10(xx), label="Degree-10 model g10(x)")
plt.title("Scenario 2: Degree 50 true polynomial (noiseless)")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.ylim(-5000, 5000) # Set wider limit for the degree 50 polynomial bounds
plt.show()

"""# PRAC4"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris, make_regression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor, plot_tree
from sklearn.metrics import accuracy_score

# ==========================================
# PART 1: Classification Example (Iris Dataset)
# ==========================================
iris = load_iris()
X = iris.data
y = iris.target

# Split data (70% training, 30% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Train models with different splitting criteria
clf_gini = DecisionTreeClassifier(criterion="gini", max_depth=3)
clf_entropy = DecisionTreeClassifier(criterion="entropy", max_depth=3)

clf_gini.fit(X_train, y_train)
clf_entropy.fit(X_train, y_train)

pred_gini = clf_gini.predict(X_test)
pred_entropy = clf_entropy.predict(X_test)

print("Accuracy (Gini):", accuracy_score(y_test, pred_gini))
print("Accuracy (Entropy):", accuracy_score(y_test, pred_entropy))

# ==========================================
# PART 2: Effect of max_depth (Overfitting vs Underfitting)
# ==========================================
depths = range(1, 11)
train_acc = []
test_acc = []

for d in depths:
    model = DecisionTreeClassifier(max_depth=d, random_state=42)
    model.fit(X_train, y_train)

    # Record accuracy for both training and test sets
    train_acc.append(accuracy_score(y_train, model.predict(X_train)))
    test_acc.append(accuracy_score(y_test, model.predict(X_test)))

# Plot Overfitting vs Underfitting
plt.figure(figsize=(8, 5))
plt.plot(depths, train_acc, label="Training Accuracy", marker='o')
plt.plot(depths, test_acc, label="Test Accuracy", marker='o')
plt.xlabel("Tree Depth")
plt.ylabel("Accuracy")
plt.title("Overfitting vs Underfitting in Decision Tree")
plt.legend()
plt.grid()
plt.show()

# ==========================================
# PART 3: Decision Tree Plot
# ==========================================
plt.figure(figsize=(12, 8))
plot_tree(
    clf_gini,
    filled=True,
    feature_names=iris.feature_names,
    class_names=iris.target_names
)
plt.title("Decision Tree Structure (Gini, max_depth=3)")
plt.show()

# ==========================================
# PART 4: Regression Example
# ==========================================
# Generate a synthetic regression dataset
Xr, yr = make_regression(
    n_samples=200,
    n_features=1,
    noise=20,
    random_state=1
)

Xr_train, Xr_test, yr_train, yr_test = train_test_split(
    Xr, yr, test_size=0.3, random_state=0
)

# Train a Decision Tree Regressor
reg = DecisionTreeRegressor(max_depth=3)
reg.fit(Xr_train, yr_train)

# Sort values for smooth plotting of the regression line
X_grid = np.sort(Xr, axis=0)
y_pred_reg = reg.predict(X_grid)

# Plot the regression tree performance
plt.figure(figsize=(8, 5))
plt.scatter(Xr, yr, label="Data")
plt.plot(X_grid, y_pred_reg, label="Regression Tree", linewidth=3, color='red')
plt.xlabel("X")
plt.ylabel("y")
plt.title("Decision Tree Regression")
plt.legend()
plt.show()

"""# prac5"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris, make_regression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, mean_squared_error

# ==========================================
# PART 1: Random Forest Classification
# ==========================================
print("--- PART 1: RANDOM FOREST CLASSIFICATION ---")
# Load Dataset
iris = load_iris()
X_c = iris.data
y_c = iris.target

# Split Data (80% training and 20% testing)
X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X_c, y_c, test_size=0.2, random_state=42)

# Train Model
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clf.fit(X_train_c, y_train_c)

# Predict and Calculate Accuracy
y_pred_c = rf_clf.predict(X_test_c)
print(f"Classification Accuracy: {accuracy_score(y_test_c, y_pred_c):.4f}")

# Feature Importance Plot
importances = rf_clf.feature_importances_
plt.figure(figsize=(8, 4))
plt.bar(range(len(importances)), importances, tick_label=iris.feature_names)
plt.title("Feature Importance (Classification)")
plt.xlabel("Features")
plt.ylabel("Importance Score")
plt.show()

# ==========================================
# PART 2: Effect of n_estimators (Overfitting)
# ==========================================
print("\n--- PART 2: OBSERVING EFFECT OF n_estimators ---")
# Testing different numbers of trees to see how the model learns/overfits
n_estimators_list = [1, 2, 5, 10, 20, 50, 100]
train_acc = []
test_acc = []

for n in n_estimators_list:
    model = RandomForestClassifier(n_estimators=n, random_state=42)
    model.fit(X_train_c, y_train_c)

    # Record accuracy for both training and test sets
    train_acc.append(accuracy_score(y_train_c, model.predict(X_train_c)))
    test_acc.append(accuracy_score(y_test_c, model.predict(X_test_c)))

# Plot the effect of n_estimators
plt.figure(figsize=(8, 5))
plt.plot(n_estimators_list, train_acc, label="Training Accuracy", marker='o')
plt.plot(n_estimators_list, test_acc, label="Test Accuracy", marker='o')
plt.xlabel("Number of Estimators (Trees)")
plt.ylabel("Accuracy")
plt.title("Effect of n_estimators on Overfitting")
plt.legend()
plt.grid(True)
plt.show()

# ==========================================
# PART 3: Random Forest Regression
# ==========================================
print("\n--- PART 3: RANDOM FOREST REGRESSION ---")
# Generate a synthetic regression dataset
X_r, y_r = make_regression(n_samples=200, n_features=1, noise=20, random_state=42)
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(X_r, y_r, test_size=0.3, random_state=42)

# Train Regressor
rf_reg = RandomForestRegressor(n_estimators=100, random_state=42)
rf_reg.fit(X_train_r, y_train_r)

# Predict and Calculate Mean Squared Error
y_pred_r = rf_reg.predict(X_test_r)
mse = mean_squared_error(y_test_r, y_pred_r)
print(f"Regression Mean Squared Error: {mse:.2f}")

# Plot Regression Line
X_grid = np.sort(X_r, axis=0)
plt.figure(figsize=(8, 5))
plt.scatter(X_r, y_r, label="Data Points", alpha=0.6)
plt.plot(X_grid, rf_reg.predict(X_grid), color='red', label="RF Regression Line", linewidth=2)
plt.xlabel("Feature X")
plt.ylabel("Target Y")
plt.title("Random Forest Regression")
plt.legend()
plt.show()

"""# prac6"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris, make_regression
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC, SVR
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn.preprocessing import StandardScaler

# ==========================================
# PART 1: SVM CLASSIFICATION
# ==========================================
print("--- PART 1: SVM CLASSIFICATION (Iris Dataset) ---")

# Load dataset
iris = load_iris()
X_cls = iris.data
y_cls = iris.target

# Feature scaling (Crucial for SVMs!)
scaler_cls = StandardScaler()
X_cls_scaled = scaler_cls.fit_transform(X_cls)

# Train-test split
X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(
    X_cls_scaled, y_cls, test_size=0.3, random_state=42
)

# Kernels to test
kernels = ['linear', 'poly', 'rbf', 'sigmoid']
train_acc = []
test_acc = []

# Train models
for k in kernels:
    model = SVC(kernel=k)
    model.fit(X_train_c, y_train_c)

    y_train_pred = model.predict(X_train_c)
    y_test_pred = model.predict(X_test_c)

    train_acc.append(accuracy_score(y_train_c, y_train_pred))
    test_acc.append(accuracy_score(y_test_c, y_test_pred))

# Print results
print("\nKernel   | Train Accuracy | Test Accuracy")
print("-" * 45)
for i, k in enumerate(kernels):
    print(f"{k:<8} | {train_acc[i]:.3f}          | {test_acc[i]:.3f}")

# Plot results
plt.figure(figsize=(8, 5))
plt.plot(kernels, train_acc, marker='o', label='Train Accuracy')
plt.plot(kernels, test_acc, marker='o', label='Test Accuracy')
plt.xlabel("Kernel Type")
plt.ylabel("Accuracy")
plt.title("SVM Classification Performance by Kernel")
plt.legend()
plt.grid(True)
plt.show()


# ==========================================
# PART 2: SVM REGRESSION
# ==========================================
print("\n--- PART 2: SVM REGRESSION (Synthetic Dataset) ---")

# Generate regression dataset
X_reg, y_reg = make_regression(
    n_samples=1000, n_features=5, noise=10, random_state=42
)

# Scale features
scaler_reg = StandardScaler()
X_reg_scaled = scaler_reg.fit_transform(X_reg)

# Train-test split
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(
    X_reg_scaled, y_reg, test_size=0.3, random_state=42
)

train_mse = []
test_mse = []

# Train models
for k in kernels:
    model = SVR(kernel=k)
    model.fit(X_train_r, y_train_r)

    y_train_pred = model.predict(X_train_r)
    y_test_pred = model.predict(X_test_r)

    train_mse.append(mean_squared_error(y_train_r, y_train_pred))
    test_mse.append(mean_squared_error(y_test_r, y_test_pred))

# Print results
print("\nKernel   | Train MSE   | Test MSE")
print("-" * 35)
for i, k in enumerate(kernels):
    print(f"{k:<8} | {train_mse[i]:<11.2f} | {test_mse[i]:.2f}")

# Plot results
plt.figure(figsize=(8, 5))
plt.plot(kernels, train_mse, marker='o', label='Train MSE')
plt.plot(kernels, test_mse, marker='o', label='Test MSE')
plt.xlabel("Kernel Type")
plt.ylabel("Mean Squared Error (Lower is better)")
plt.title("SVM Regression Performance by Kernel")
plt.legend()
plt.grid(True)
plt.show()

# ==========================================
# FINAL OBSERVATIONS
# ==========================================
print("\n=== FINAL OBSERVATIONS ===")
print("CLASSIFICATION (IRIS):")
print("- Linear kernel works well for linearly separable data.")
print("- RBF kernel usually gives best performance for complex boundaries.")
print("- Polynomial kernel can capture non-linearity but may overfit depending on the degree.")
print("- Sigmoid kernel often performs poorly on this dataset.")

print("\nREGRESSION:")
print("- Linear kernel works best here because 'make_regression' strictly generates a linear dataset.")
print("- RBF and Polynomial kernels show much higher MSE (worse performance) because they are trying to fit complex curves to simple straight-line data.")

"""# prac7"""

# 1. GROUPED IMPORTS
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.metrics import accuracy_score
import warnings

# Suppress the collinearity warnings for a cleaner output
warnings.filterwarnings("ignore")

# 2. LOAD & PREP
# The digits dataset is built into sklearn
X, y = load_digits(return_X_y=True)

# Split the data (70% training, 30% testing as per your original code)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# 3. THE MODEL LOOP
# Put both initialized models into a dictionary
models = {
    "LDA": LinearDiscriminantAnalysis(),

    # Note: QDA often throws a "covariance matrix is not full rank" warning on this dataset.
    # We added reg_param=0.0001 to slightly regularize it and stop the math from breaking.
    "QDA": QuadraticDiscriminantAnalysis(reg_param=0.0001)
}

# Loop through the dictionary, fit, predict, and print!
print("--- LDA vs QDA on Digits Dataset ---")
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"{name} Accuracy: {acc:.4f}")

"""# prac8"""

import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans

# ==========================================
# PART 1: LOAD & PREP DATA
# ==========================================
print("--- PREPARING DATA ---")
# We only need X (features), not y (labels), because clustering is unsupervised.
# We slice [:, :2] to grab only the first two columns (Sepal Length & Width) to easily plot in 2D.
X, _ = load_iris(return_X_y=True)
X_2d = X[:, :2]

# ==========================================
# PART 2: ELBOW METHOD (Finding the optimal k)
# ==========================================
print("--- RUNNING ELBOW METHOD ---")
inertia = []
K_range = range(1, 11)

for k in K_range:
    # Explicitly setting n_init=10 prevents annoying FutureWarnings in newer sklearn versions
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    inertia.append(kmeans.fit(X_2d).inertia_)

# Plot the Elbow Graph
plt.figure(figsize=(8, 5))
plt.plot(K_range, inertia, marker='o')
plt.title('Elbow Method to Find Optimal k')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia (Sum of Squared Distances)')
plt.grid(True)
plt.show()

# ==========================================
# PART 3: VISUALIZE CLUSTERS
# ==========================================
print("\n--- VISUALIZING CLUSTERS (k=2, k=3, k=5) ---")
# We test 2, 3 (which the elbow method shows is optimal), and 5.
for k in [2, 3, 5]:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    clusters = kmeans.fit_predict(X_2d)

    plt.figure(figsize=(8, 5))
    # Plot the data points colored by their assigned cluster
    plt.scatter(X_2d[:, 0], X_2d[:, 1], c=clusters, cmap='viridis', alpha=0.8)

    # Draw the red 'X' centroids specifically for the optimal k=3 plot (matching your PDF)
    if k == 3:
        centroids = kmeans.cluster_centers_
        plt.scatter(centroids[:, 0], centroids[:, 1], s=200, marker='X', c='red', label='Centroids')
        plt.legend()

    plt.title(f"K-Means with k = {k}")
    plt.xlabel('Sepal Length')
    plt.ylabel('Sepal Width')
    plt.show()

"""# prac9"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# ==========================================
# PART 1: LOAD & SCALE DATA
# ==========================================
print("--- LOADING AND SCALING DATA ---")
wine = load_wine()
X, y, features = wine.data, wine.target, wine.feature_names

# Standardization is absolutely mandatory for PCA so that features
# with larger scales (like 'proline') don't dominate the components.
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# ==========================================
# PART 2: APPLY PCA
# ==========================================
# Apply PCA keeping all components first to calculate variance
pca = PCA()
X_pca = pca.fit_transform(X_scaled)

# Calculate the cumulative explained variance
cumulative_variance = np.cumsum(pca.explained_variance_ratio_)

# ==========================================
# PART 3: SCREE PLOT
# ==========================================
print("--- PLOTTING SCREE PLOT ---")
plt.figure(figsize=(8, 5))
plt.plot(cumulative_variance, marker='o')
plt.title("Scree Plot (Cumulative Variance)")
plt.xlabel("Number of Components")
plt.ylabel("Cumulative Explained Variance")
plt.grid(True)
plt.show()

# ==========================================
# PART 4: 2D PROJECTION PLOT
# ==========================================
print("\n--- PLOTTING 2D PCA PROJECTION ---")
# To plot in 2D, we just slice the first two columns of the PCA result
plt.figure(figsize=(8, 5))
scatter = plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y, cmap='viridis')
plt.title("PCA Projection (2D)")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.legend(*scatter.legend_elements(), title="Classes")
plt.grid(True)
plt.show()

# ==========================================
# PART 5: FEATURE IMPORTANCE & VARIANCE RETAINED
# ==========================================
# pca.components_ contains the eigenvectors. We just slice the first 2 rows.
components_df = pd.DataFrame(pca.components_[:2, :], columns=features, index=["PC1", "PC2"])

print("\n--- PRINCIPAL COMPONENT WEIGHTS (First 2 PCs) ---")
print(components_df.T) # Transposed for easier reading in the console

# Print how much of the original data's variance is retained by just 2 components
print(f"\nVariance Retained by 2 Components: {cumulative_variance[1]:.4f}")

"""# prac10"""

import warnings
warnings.filterwarnings("ignore") # This completely hides the ConvergenceWarnings!

import matplotlib.pyplot as plt
from sklearn.datasets import load_digits, load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.metrics import accuracy_score, mean_squared_error

# ==========================================
# --- PART A: CLASSIFICATION (Digits) ---
# ==========================================

# 1. Load & Prep
X, y = load_digits(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 2. Base Model & Plot
clf = MLPClassifier(hidden_layer_sizes=(100,), max_iter=50, random_state=42)
clf.fit(X_train, y_train)
print("Base Accuracy:", accuracy_score(y_test, clf.predict(X_test)))

plt.plot(clf.loss_curve_)
plt.title("Classification Training Loss")
plt.show()

# 3. Hyperparameter Loops (Condensed)
params_to_test = {
    'activation': ['relu', 'logistic', 'tanh'],
    'hidden_layer_sizes': [(50,), (100,), (50, 50)],
    'solver': ['adam', 'sgd'],
    'learning_rate_init': [0.001, 0.01]
}

for param_name, values in params_to_test.items():
    for val in values:
        model = MLPClassifier(**{param_name: val}, max_iter=50, random_state=42)
        model.fit(X_train, y_train)
        acc = accuracy_score(y_test, model.predict(X_test))
        print(f"{param_name} = {val} | Accuracy: {acc}")

# 4. Early Stopping Test
early_stop_model = MLPClassifier(early_stopping=True, validation_fraction=0.2, max_iter=200, random_state=42)
early_stop_model.fit(X_train, y_train)
print("Early Stopping Accuracy:", accuracy_score(y_test, early_stop_model.predict(X_test)))


# ==========================================
# --- PART B: REGRESSION (Diabetes) ---
# ==========================================

# 1. Load & Prep (Reusing the scaler from above)
X_reg, y_reg = load_diabetes(return_X_y=True)
X_tr, X_te, y_tr, y_te = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)

X_tr = scaler.fit_transform(X_tr)
X_te = scaler.transform(X_te)

# 2. Model, Predict & Plot
reg = MLPRegressor(hidden_layer_sizes=(100,), max_iter=100, random_state=42)
reg.fit(X_tr, y_tr)
print("MSE:", mean_squared_error(y_te, reg.predict(X_te)))

plt.plot(reg.loss_curve_)
plt.title("Regression Training Loss")
plt.show()